[application]
type = "token"
owner = 1234567891234567891
guild = 1234567891234567891
privileged = []

[application.credentials]
token = "<token>"

[database]
type = "sqlite"
host = "default.sqlite"
port = -1
name = ""

[database.credentials]
username = ""
password = ""

